Implement forwarding protocol
ContainerSSH/agent pull request #4
Opened 2022-03-28 17:26 UTC by tsipinakis

## Please describe the change you are making

Implement a protocol for connection forwarding

## Are you the owner of the code you are sending in, or do you have permission of the owner?

Sent with permission from the owner

## The code will be published under the MIT-0 license. Have you read and understood this license?

Yes

2022-03-28 20:02 UTC, janosdebugs requested changes
Looks good, but a few things may need some work.

2022-03-28 20:02 UTC, janosdebugs commented on forwardServer.go
> +			str := fmt.Sprintf("=== received SIGQUIT ===\n*** goroutine dump...\n%s\n*** end\n", buf[:stacklen])
We should think about a good way to serialize these in the log library. Logging this kind of stuff may prove tricky with syslog if we ever decide to add it.

2022-03-28 20:02 UTC, janosdebugs commented on forwardServer.go
> +	//ctx := proto.ForwardCtx{
!!! commented out code!

2022-03-28 20:02 UTC, janosdebugs commented on go.mod
> +	github.com/fxamacker/cbor/v2 v2.3.0
Please use the latest version, they are working hard on stability improvements.

2022-03-28 20:11 UTC, tsipinakis commented on protocol/Protocol.go
> +package protocol
There already is a unified library for the protocol, `server.go` :)

2022-03-28 20:18 UTC, tsipinakis commented on forwardServer.go
> +		return host + ":" + strconv.Itoa(int(port))
It should, host can also be a dns hostname so if there's an ipv6 address in there it should be properly escaped.

2022-03-28 20:29 UTC, janosdebugs commented on protocol/Protocol.go
> +package protocol
We still need to move it to avoid a circular dependency.

2022-06-03 18:51 UTC, janosdebugs commented
@tsipinakis now that libcontainerssh is merged can we get this sorted?

2022-06-07 08:29 UTC, tsipinakis commented
Need to merge https://github.com/ContainerSSH/libcontainerssh/pull/142 before finishing this.

2023-06-30 11:21 UTC, closed without merging